# tf.data 数据处理




In [2]:
import tensorflow as tf

In [12]:
dataset1 = tf.data.Dataset.from_tensor_slices(tf.random_uniform([4, 10]))

print(dataset1.output_types)
print(dataset1.output_shapes)

<dtype: 'float32'>
(10,)


In [20]:
dataset = tf.data.Dataset.range(100)
iterator = dataset.make_one_shot_iterator()
next_element = iterator.get_next()

sess = tf.Session()

for i in range(100):
    value = sess.run(next_element)
    assert i ==value

# with tf.Session() as sess:
#     for i in range(100):
#        value = sess.run(next_element)
#        print(value)
#        assert i == value

In [29]:
r = tf.random_normal([10,3])
dataset = tf.data.Dataset.from_tensor_slices(r)
iterator = dataset.make_initializable_iterator()
next_row = iterator.get_next()

sess.run(iterator.initializer)
while True:
  try:
    print(sess.run(next_row))
  except tf.errors.OutOfRangeError:
    break

[-0.01003916  0.5132673  -0.2481137 ]
[ 0.0799829 -1.3136768 -0.2202952]
[ 1.8486434  -0.56629455 -1.1719214 ]
[ 0.4812373   0.05030565 -0.5615767 ]
[ 0.37247312 -1.161068   -0.92452383]
[ 0.60864973 -0.48032036 -0.8421415 ]
[ 0.6974423 -1.6399066  2.62417  ]
[-0.03768973 -0.44170484  1.1433735 ]
[-0.4015822  -0.996073    0.12635642]
[1.0110908  0.33185467 0.07822055]
